apiVersion: v1
kind: Service
metadata:
  name: billsplit-service
spec:
  type: NodePort
  ports:
    - targetPort: 3030
      port: 3030
      nodePort: 30008
  selector:
    app: billsplit-deployment
